### PR TITLE
Fixed some improper escaping of an &amp; in a couple of elements

### PR DESCRIPTION
**Pull request by Vadoola**

### CODE REVIEW

**Comment by scorpio810** [comment]
Hello,

I think you can delete these element
endress&hauser-sonde-pression-deltapilot-s.elmt
endress&hauser-niveau-capacitif-ec11z-.elmt

Can't drag and drop in diagram "not valid XML" warning if I open directly in file navigator.

**Comment by Vadoola** [comment]
I was doing some testing for dxf2elmt against existing elements when I also got an XML parsing error on these two files.

This patch seems to fix that...although now that I look again maybe not. Trying to parse these two files after my change in this pull request parses as valid XML, and if I open the elmts directly with the element editor from the file navigatorthey seem to open just fine. That's when I decided to submit this patch.

However just now I opened QElectrotech, tried to create a drawing and add these elements. The Library seems to show the wrong thumbnail and like you are saying it won't let me add them to a drawing. I'm not sure what's going on there, if this is some caching issue, or something else is wrong with the XML still.

If I get the chance later, I can try and take a closer look into it. If you don't think they are worth keeping around I am fine with them being deleting, I have no use for them myself, but I imagine they were added because at some point someone needed them.

**Comment by scorpio810** [comment]
#However just now I opened QElectrotech, tried to create a drawing and add these elements. The Library seems to show the wrong thumbnail and like you are saying it won't let me add them to a drawing. I'm not sure what's going on there, if this is some caching issue, or something else is wrong with the XML still.

Try right click on collection -> reload collection.

**Comment by scorpio810** [comment]
Maybe you can fixing the improper escaping of &amp in the others language name of the element

**Comment by plc-user** [comment]
Hello Vadoola!
Salut Laurent !

With the changes you made, these elements are valid XML and they can be used in QET.

The other thing with the "wrong" thumbnails has some other reason:
The UUIDs of the elements were doubles of other ones!

I grepped the elements-collection for the UUIDs of the elements and saw that 12 elements had the same UUID as 12 other ones. I corrected them manually and now I think everything should be fine with the UUIDs.

In this context, I also "repaired" the three elements mentioned by Vadoola and uploaded them as well. This PR can therefore be closed without rejecting Vadoola's suggestions!

**Comment by Vadoola** [comment]
Thanks for that. I haven't had as much time recently as I had hoped, and what time I did have I was spending on my changes to dxf2elmt, so I just hadn't looked deeper into this.

**Pull request closed without merging**
